### ISSUE TITLE
Issue with Cyrillic characters

### ISSUE THREAD

**Issue by lazarevski** [tomik23/show-more#14]
Truncating Cyrillic characters does not work. Trying to truncate a mixed paragraph (cyr+lat), and the truncated text only shows the Latin characters. Upon clicking 'show more' the full text is displayed. Same goes if the full text is Cyrillic only: the truncated text shows nothing, and full text on 'show more'.

**Comment by tomik23** [comment]
Thanks for catching it, I'll check it out.

**Comment by lazarevski** [comment]
Tnx for fixing this so quick.
