### ISSUE TITLE
Option to show an ellipsis together with a "read more" button.

### ISSUE THREAD

**Issue by lazarevski** [tomik23/show-more#21]
Currently, as far as I can tell, an ellipsis is only visible if there is no read more/expand button. It would be nice if the truncated text is followed by an ellipsis and then the expand button.

> Lorem ipsum dolor sit amet, consectetur adipiscing... → read more

**Comment by tomik23** [comment]
Thanks for the suggestion, I'll try to include it in the future.

**Comment by tomik23** [comment]
Adding an ellipsis to the text by default #22 
You can of course disable the ellipsis by adding the parameter `"ellipsis": false`
