### ISSUE TITLE
improve config 

### ISSUE THREAD

**Issue by ppppfly** [tomik23/show-more#48]
```javascript
const {
  type,
  limit,
  element,
  after,
  more,
  less,
  number,
  ellipsis,
  btnClass,
  btnClassAppend
} = JSON.parse(elements[i].getAttribute('data-config')) || config;
```
currently, the config is either set on `data-config` or use global setting in initial.

is it ok that, if both global config and `data-config` is setup, then use the combine config. In this case, the global config will be the base config for all usage in the page, and `data-config` will the individual for each usage.

**Comment by tomik23** [comment]
Thanks for the idea. In version 1.1.3 link two objects, global configuration + data-config.
What is the benefit of this, if there are less/more elements in globalen configuration I don't need to add them to `data-config` anymore.

```html
<div class = "item" data-config = '{"limit": 20}'>
   Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quo, deleniti?
</div>
```

```js
new ShowMore ('. element', {
   config: {
     type: "text",
     limit: 200,
     more: "→ read more",
     less: "← read less"
   }
});
```

The object from `data-config` overwrites the elements from the `global configuration` in the above example the limit element will be set to 20, not 200 characters.

In this way, we can overwrite all elements from the global configuration.
