### ISSUE TITLE
number: true does not work for inline lists (<li>)

### ISSUE THREAD

**Issue by ivanionut** [tomik23/show-more#56]
Hello @tomik23,
as I wrote in the title, `"number": true` does not work for inline lists (`<li>`)

**Comment by tomik23** [comment]
Give an example of what doesn't work for you.

**Comment by ivanionut** [comment]
hi @tomik23,
look here: https://playcode.io/966306

**Comment by tomik23** [comment]
You are right this example does not work, just why?
The example page displays a number.
Ok, I'll try to see it in the evening.

**Comment by tomik23** [comment]
So I checked quickly and this problem arises when class is given on li elements. When I removed these classes from li, a number appeared.
